import header from "./header-image.jpg";
import bannerAvatar from "theme/images/bannerTitle.png";
import phoneImage from "theme/images/khamtuxa.png";
import phoneImage1 from "theme/images/khamtongquat.png";
import phoneMage from "theme/images/dichvuxetnghiem.png";
import phoneFf from "theme/images/khamnhakhoa.png";
import phoneFfg from "theme/images/phauthuat.jpg";
import sliderTest from "theme/images/slider-slick.jpg";
import imageLogin from "theme/images/FrameLogin.png";
export { header, bannerAvatar, phoneImage, phoneImage1, phoneMage, phoneFf, phoneFfg, sliderTest, imageLogin };
